version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    target-branch: main
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-minor
          - version-update:semver-patch
    groups:
      major-releases:
        update-types:
          - major

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    target-branch: main
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-minor
          - version-update:semver-patch
    groups:
      major-releases:
        update-types:
          - major
